version: '3.8'

services:
  backend:
    build:
      context: ./go-backend
    container_name: go_backend
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "1323:1323"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./angular-frontend
    container_name: angular_frontend
    ports:
      - "4200:4200"  # Map port 4200 on the host to port 4200 in the container

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
